# -*- coding: utf-8 -*-
"""OS_proj2_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11RMPub78Y_v62rWK4lgJInD-S6EsoXsi
"""

import pandas as pd

df = pd.read_csv('/content/sample_data/2019_kbo_for_kaggle_v2.csv')

# 2-1-1
for year in range(2015, 2019):
     print(f"\n{year}년 : ")

     this_y = df[df['year'] == year]

     for category in ['H', 'avg', 'HR', 'OBP']:
         print(f"\nTop 10 플레이어 in {category}:")

         this_y_sort = this_y.sort_values(by=category, ascending=False)
         this_y_sort['Rank'] = this_y_sort[category].rank(ascending=False, method='min')

         top10_players = this_y_sort[this_y_sort['Rank'] < 11]
         print(top10_players[['batter_name', category]].to_string(index=False, header=False))

# 2-1-2

df_2018 = df[df['year'] == 2018]
max_war_position = df_2018[df_2018['cp'] != '지명타자'].groupby('cp')['war'].idxmax()

result_df = df_2018.loc[max_war_position, ['cp', 'batter_name', 'war']]
result_df = result_df.reset_index(drop=True)
print(result_df.to_string(index=False, header=False))

# 2-1-3

columns = ['R', 'H', 'HR', 'RBI', 'SB', 'war', 'avg', 'OBP', 'SLG']
correlations = df[columns].corrwith(df['salary'])
max_correlations_column = correlations.abs().idxmax()
print(f"'salary'와 가장 correlation 높은 지표는'{max_correlations_column}'")